conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: colorization_soc
    in_shape: !!python/tuple [1, 3, 256, 256]
  
  noise: 
    name: gaussian
    sigma: 0.05