conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: inpainting_soc
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [128, 129]  # for box
    # mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 256

  scale:
    linear:
      box: 0.6
      random: 0.8
      nonlinear_finitegamma: 1
    nonlinear:
      box: 0.7
      random: 0.8
      nonlinear_finitegamma: 1


  noise:
    name: gaussian
    sigma: 0.05
