conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: motion_blur_soc
    kernel_size: 61
    intensity: 0.5

  scale:
    linear: 0.7
    nonlinear: 0.7
    nonlinear_finitegamma: 1

  noise: 
    name: gaussian
    sigma: 0.05
