conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: nonlinear_blur_soc
    opt_yml_path: ./bkse/options/generate_blur/default.yml

  scale:
    linear: 0.7
    nonlinear: 0.7
    nonlinear_finitegamma: 1

  noise: 
    name: gaussian
    sigma: 0.05
